use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use async_trait::async_trait;

use crate::error::AppError;

/// Result type for OTP operations.
pub type OtpResult<T> = Result<T, AppError>;

/// Trait for OTP delivery providers.
///
/// Implementations are responsible for delivering a one-time code to the
/// recipient identified by `destination` (e.g. an email address or phone
/// number). The code itself is generated by the caller so that challenge
/// storage and delivery stay decoupled.
#[async_trait]
pub trait OtpProvider: Send + Sync {
    /// Deliver `code` to `destination`.
    async fn send_code(&self, destination: &str, code: &str) -> OtpResult<()>;
}

/// A no-op OTP provider used in tests and local development.
///
/// Instead of delivering the code over a real channel, the mock records every
/// sent code in a thread-safe store so that tests can retrieve it and complete
/// the verification step end-to-end.
#[derive(Clone, Default)]
pub struct MockOtpProvider {
    sent: Arc<Mutex<HashMap<String, String>>>,
}

impl MockOtpProvider {
    /// Create a new, empty mock provider.
    pub fn new() -> Self {
        Self {
            sent: Arc::new(Mutex::new(HashMap::new())),
        }
    }

    /// Return the most recently sent code for `destination`, if any.
    pub fn last_code(&self, destination: &str) -> Option<String> {
        self.sent
            .lock()
            .expect("mock otp store poisoned")
            .get(destination)
            .cloned()
    }

    /// Return a snapshot of every code sent so far, keyed by destination.
    pub fn sent_codes(&self) -> HashMap<String, String> {
        self.sent
            .lock()
            .expect("mock otp store poisoned")
            .clone()
    }

    /// Clear all captured codes. Useful between test cases.
    pub fn clear(&self) {
        self.sent
            .lock()
            .expect("mock otp store poisoned")
            .clear();
    }
}

#[async_trait]
impl OtpProvider for MockOtpProvider {
    async fn send_code(&self, destination: &str, code: &str) -> OtpResult<()> {
        self.sent
            .lock()
            .expect("mock otp store poisoned")
            .insert(destination.to_string(), code.to_string());
        tracing::info!(destination = %destination, "mock otp code captured");
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn mock_provider_captures_sent_code() {
        let provider = MockOtpProvider::new();
        provider.send_code("user@example.com", "123456").await.unwrap();

        assert_eq!(
            provider.last_code("user@example.com"),
            Some("123456".to_string())
        );
        assert_eq!(provider.sent_codes().len(), 1);

        provider.clear();
        assert!(provider.last_code("user@example.com").is_none());
    }
}
